services:
  postgres:
    image: postgres:16
    env_file:
      - .env
    ports:
      - "5440:5432"
    networks:
      - mynetwork

  erp-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - mynetwork

networks:
  mynetwork: