version: '3.8'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: erp_user
      POSTGRES_PASSWORD: Pedro@110904
      POSTGRES_DB: erp_db
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  erp-app:
    image: erp_image:v1.0
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - mynetwork
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/erp_db
      SPRING_DATASOURCE_USERNAME: erp_user
      SPRING_DATASOURCE_PASSWORD: Pedro@110904

networks:
  mynetwork: